version: '3.8'

services:
  recipe:
    image: iamsanuj/recipe:latest
    build:
      context: .
    container_name: recipe_container
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - recipe_overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  recipe_overlay:
    driver: overlay
